name: CI_Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - vishnu
    
jobs:
   build:
      name: server_details
      runs-on: ubuntu-22.04

      steps:
      - uses: actions/checkout@v4
      - name: first_step
        run: |
           echo "Calling First step in build job"
           echo "Build complted successfully"
   test:
     runs-on: ubuntu-22.04
     needs: build
     steps:
       - name: Calling Test job
         run: |
           echo "Running Testing job"
           echo "The OS distro is... `cat /etc/os-release`"
   deploy:
     runs-on: ubuntu-slim
     needs:
       - build
       - test
     steps:
       - name: Deploying an app
         run:
           echo "Deployment is succesful on `hostname`"
   validate:
     runs-on: ubuntu-latest
     steps:
       - name: Validating Build job
         run: |
           sleep 10
           echo "Validating Job on build server"
