name: CI_Workflow
on:
  push:
    branches:
    - vishnu
  workflow_dispatch:
    
jobs:
   build:
      name: server_details
      runs-on: vishnu

      steps:
      - uses: actions/checkout@v4
      - name: first_step
        run: |
           echo "Calling First step in build job"
           echo "Build complted successfully"
   test:
     runs-on: ubuntu-22.04
     needs: build
     steps:
       - name: Calling Test job
         run: |
           echo "Running Testing job"
           echo "The OS distro is... `cat /etc/os-release`"
   deploy:
     runs-on: ubuntu-slim
     needs:
       - build
       - test
     steps:
       - name: Deploying an app
         run:
           echo "Deployment is succesful on `hostname`"
