name: Fetch Host Details
on:
 workflow_dispatch:
 push:
   branches:
     - priyanka
jobs:
 fetch:
  runs-on: ubuntu-22.04-arm
  steps:
    - continue-on-error: true
      id: A_23
      run: echo "The job is running on $(hostname)"
           echo "Successfully fetched the host details"
      
      
      
      
