name: Demo of Matrix Strategy
on:
 workflow_dispatch:
 push:
   branches:
     - priyanka
jobs:
 runOnMultipleOS:
  runs-on: ${{matrix.os}}
  strategy:
    matrix: 
      os: [ubuntu-22.04-arm, ubuntu-24.04, ubuntu-latest]
  steps:
    - name: Running on multiple OS
      run: echo "Running the script using multiple OS $(hostname)"
      
      
      
